# Generated by Django 4.0.6 on 2022-08-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_usertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
