# Generated by Django 4.0.6 on 2022-08-09 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subject_id', models.IntegerField()),
                ('subject_name', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='standard',
            fields=[
                ('standard_school_id', models.CharField(blank=True, max_length=100, null=True)),
                ('standard_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('standard_name', models.CharField(db_index=True, max_length=20)),
                ('standard_password', models.CharField(max_length=50)),
                ('standard_phone', models.CharField(max_length=10)),
                ('standard_email', models.EmailField(max_length=254)),
                ('standard_subject', models.ManyToManyField(to='standard.subject')),
            ],
        ),
    ]
