# Generated by Django 4.0.6 on 2022-08-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='standard_id',
            field=models.CharField(blank=True, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='standard_password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
