# Generated by Django 4.0.6 on 2022-08-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0003_usertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard',
            old_name='standard_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='standard_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='standard_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='standard_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='standard_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='standard_school_id',
            new_name='school_id',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='standard_subject',
            new_name='subject',
        ),
    ]
