# Generated by Django 4.0.6 on 2022-08-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0006_alter_standard_school_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard',
            old_name='school_id',
            new_name='schoolId',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_id',
            new_name='subjectId',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='subjectName',
        ),
    ]
