# Generated by Django 4.0.6 on 2022-08-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0008_rename_id_standard_classid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard',
            old_name='name',
            new_name='className',
        ),
        migrations.AddField(
            model_name='standard',
            name='teacherName',
            field=models.CharField(default=4, max_length=50),
            preserve_default=False,
        ),
    ]
