# Generated by Django 4.0.6 on 2022-08-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0009_rename_name_standard_classname_standard_teachername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='subject',
        ),
    ]
