# Generated by Django 4.0.6 on 2022-08-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0010_remove_standard_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='profilePhoto',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
