# Generated by Django 4.0.6 on 2022-08-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0004_rename_standard_email_standard_email_and_more'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='standard_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='standard.standard'),
        ),
    ]
