# Generated by Django 4.0.6 on 2022-08-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_school_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admission_date',
            new_name='admissionDate',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='school_id',
            new_name='schoolId',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='standard_id',
            new_name='standardId',
        ),
        migrations.RemoveField(
            model_name='student',
            name='result',
        ),
    ]
