# Generated by Django 4.0.6 on 2022-08-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_id_student_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profilePhoto',
            field=models.ImageField(default=5, upload_to=None),
            preserve_default=False,
        ),
    ]
