# Generated by Django 4.0.6 on 2022-08-22 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('standard', '0008_rename_id_standard_classid'),
        ('student', '0006_rename_id_student_studentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='categori',
            fields=[
                ('catId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('catName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('lvlId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('lvlName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('subCatId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subCatName', models.CharField(max_length=100, unique=True)),
                ('catName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nonacadamin.categori')),
            ],
        ),
        migrations.CreateModel(
            name='participation',
            fields=[
                ('coCurricularId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('isVerified', models.BooleanField(default=False)),
                ('level', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('studentName', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nonacadamin.categori')),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='standard.standard')),
                ('schoolId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nonacadamin.subcategory')),
            ],
        ),
    ]
