# Generated by Django 4.0.6 on 2022-08-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonacadamin', '0002_alter_participation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
