# Generated by Django 4.0.6 on 2022-08-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonacadamin', '0004_alter_participation_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='points',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
