# Generated by Django 4.0.6 on 2022-08-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonacadamin', '0006_alter_participation_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='catName',
            new_name='catId',
        ),
    ]
